apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
stringData:
  PORT: "5000"
  NODE_ENV: "production"

  # Mongo full URI
  MONGO_URI: "mongodb://mongo:27017/swiftDrop"

  # JWT
  JWT_SECRET: "swift2233##dr3o4p"

  # Redis full URL
  REDIS_HOST: "redis"
  REDIS_DB_PORT: "6379"
